### ISSUE TITLE
split parser.py into individual tld files

### ISSUE THREAD

**Issue by fawaf** [richardpenman/whois#117]
since the file is nearly 3000 lines long.

also allows for easier new tld/patch submissions.

**Comment by richardpenman** [comment]
good idea - feel free to submit a PR for this

**Comment by fawaf** [comment]
why was this issue closed? doesn't seem to be completed yet

**Comment by richardpenman** [comment]
feel free to submit a PR for this. I don't keep PR's for feature requests open because a lot of people have ideas but few are willing to implement them.

**Comment by mzpqnxow** [comment]
FYI, I have a fork that dynamically loads the modules from a package directory using `importlib`. This avoids the need to:

1. Have hundreds of imports, one for each tld-specific `WhoisEntry` class
2. Have a gigantic `if ... elif ... elif ... elif ...` block

To avoid the `if ... elif ... elif ...`, I added a property to the `WhoisEntry` classes to specify the domain- e.g.

```python
class WhoisCom(WhoisEntry):
    """Whois parser for .com domains
    """
    TLD = '.com'
    not_found = 'No match for "'
    regex = { ... }
    ...
```

When the main package is loaded, a mapping is created of TLD -> (domain-specific) `WhoisEntry` class. This way rather than the conditional block, it just tries to pull from the mapping, and if not found, returns a fallback `WhoisEntry` class. In the end it's functionally equivalent to the way it works now

I considered submitting this as a PR but it's relatively invasive and I haven't had the time to properly test it (I use it for thousands of TLDs and gTLDs regularly, but this doesn't really suffice for proper testing)

@richardpenman do you have the appetite for changes of this magnitude or is that something you'd like to avoid at the moment? I realize you're probably managing this project entirely on your own with little or no sponsorship (and that's appreciated, by the way)

I figure one of the three are the options:

1. Submit as PR to master
2. Submit as PR to some alpha/development branch
3. Maintain a public fork, adhering to the license and credit requirements (and maybe eventually merging upstream at some point)

**Comment by richardpenman** [comment]
@mzpqnxow yes I would be happy with a PR for this using `pgkutil`!
