### ISSUE TITLE
It's time to release a new version in pypi!

### ISSUE THREAD

**Issue by ev01ing** [richardpenman/whois#191]
It's time to release a new version in pypi!

**Comment by adamcysec** [comment]
i agree!

**Comment by liquidsec** [comment]
Please, there are still print() statements for errors in the pypi package, which have long since been converted to proper logger events.

When this repo is being used by downstream pypi packages, pypi prevents pinning to a github branch. Which means, as a downstream consumer we are totally stuck with what is published in pypi if we also want to be published to pypi.

**Comment by richardpenman** [comment]
Sorry for delay - busy with babies and all that. Updated pypi.
