### ISSUE TITLE
DepractionWarning from implicitly required module imp

### ISSUE THREAD

**Issue by kidmose** [richardpenman/whois#38]
The `from future import standard_library`, that is widely used here in `pywhois`, hits an `import imp` in the future module [here](https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L65), which in my test setup results in a `DeprecationWarning` (my setup: `pytest`, Python 3.7.0, pytest-5.3.5, py-1.8.1, pluggy-0.13.1). I would like to use `pywhois` in my project, but the warning is undesirable...

I don't see a simple fix for this (If there is, I'd like pointers on how to contribute with it!) so I'm instead raising the question; Is it about time to drop support for py2 and thereby make it possibly to remove `future` as a dependency of `pywhois`?

From my point of view, py2 is dead and gone, so those who cling to it should not expect to get updates in libraries like `pywhois`.

**Comment by richardpenman** [comment]
sorry I would like to keep python2 - some people aren't able to upgrade

**Comment by elderlabs** [comment]
Python 3.12 is coming. It will drop all support for `imp`, thus I must suggest a compromise.

Many packages maintain support for the long-deprecated Python2 without the use of `imp`. While I myself do not, there are alternative means to maintaining support for both sides, otherwise `python-whois` will end with the release of Python 3.12. As I and many others would not like to see that, I'd like to correct this issue somewhere in the pipeline.

Packages like `six` might offer some amount of support, though I have not checked. I'll look into correcting the issue in `python-future` directly, though testing the patch would be fairly impossible as I do not use it myself.

**Comment by elderlabs** [comment]
Python 3.12 is coming. It will drop all support for `imp`, thus I must suggest a compromise.

Many packages maintain support for the long-deprecated Python2 without the use of `imp`. While I myself do not, there are alternative means to maintaining support for both sides, otherwise `python-whois` will end with the release of Python 3.12. As I and many others would not like to see that, I'd like to correct this issue somewhere in the pipeline.

Packages like `six` might offer some amount of support, though I have not checked. I'll look into correcting the issue in `python-future` directly, though testing the patch would be fairly impossible as I do not use it myself.

**Comment by AngellusMortis** [comment]
Just another bump on this. Python 3.12 comes out in less then 3 months. This package and everything that uses it will stop working unless this deprecation is fixed.
